// The permission catalogue. Roles grant permissions; screens and API routes check them.

export interface ModuleDef { id: string; name: string; desc: string; icon: string }
export const MODULES: ModuleDef[] = [
  { id: 'crm', name: 'CRM & pipeline', desc: 'Customers, leads, opportunities, activity', icon: 'icon-kanban' },
  { id: 'sales', name: 'Sales & quotations', desc: 'Quotes, discounts, conversion to projects', icon: 'icon-scroll-text' },
  { id: 'projects', name: 'Projects & milestones', desc: 'Engagements, schedules, billing plans', icon: 'icon-folder-kanban' },
  { id: 'tasks', name: 'Tasks & assignments', desc: 'Work items, owners, due dates', icon: 'icon-list-checks' },
  { id: 'billing', name: 'Billing & invoicing', desc: 'Invoices, credit notes, GST', icon: 'icon-file-text' },
  { id: 'payments', name: 'Payments & receivables', desc: 'Receipts, allocation, ageing', icon: 'icon-wallet' },
  { id: 'assets', name: 'Assets', desc: 'Equipment, assignment, returns', icon: 'icon-laptop' },
  { id: 'documents', name: 'Documents', desc: 'Files attached to any record', icon: 'icon-folder' },
  { id: 'approvals', name: 'Approvals', desc: 'Policies and decision queues', icon: 'icon-badge-check' },
  { id: 'reports', name: 'Reports', desc: 'Revenue, utilisation, ageing', icon: 'icon-chart-column' },
  { id: 'ai', name: 'AI assistant', desc: 'Summaries, plans, drafted updates', icon: 'icon-sparkles' },
];

export interface PermGroup { area: string; name: string; mod: string | null; icon: string; perms: [string, string][] }
export const PERM_GROUPS: PermGroup[] = [
  { area: 'customer', name: 'Customers', mod: 'crm', icon: 'icon-building-2', perms: [['customer.read', 'See customers, their contacts and their addresses'], ['customer.create', 'Add a customer'], ['customer.update', 'Change a customer’s details, including their GSTIN and payment terms'], ['customer.archive', 'Archive a customer so they stop appearing on new documents']] },
  { area: 'quote', name: 'Quotations', mod: 'sales', icon: 'icon-scroll-text', perms: [['quote.read', 'See quotations and what they offer'], ['quote.create', 'Draft a quotation'], ['quote.update', 'Change a quotation that is still a draft'], ['quote.approve', 'Approve a quotation someone else submitted, so it can be sent'], ['quote.approve_own', 'Approve a quotation you drafted yourself'], ['quote.reject', 'Send a quotation back to its author'], ['quote.send', 'Send an approved quotation to the customer'], ['quote.convert', 'Turn an accepted quotation into a project or an invoice']] },
  { area: 'catalog', name: 'Catalogue', mod: 'sales', icon: 'icon-package', perms: [['catalog.read', 'See catalogue items and their standard rates'], ['catalog.manage', 'Add items and change standard rates']] },
  { area: 'project', name: 'Projects', mod: 'projects', icon: 'icon-folder-kanban', perms: [['project.read', 'See projects and their milestones'], ['project.create', 'Start a project'], ['project.update', 'Change a project’s details and contract value'], ['project.change_owner', 'Hand a project to somebody else, making them answerable for it'], ['project.assign_members', 'Add and remove people on a project']] },
  { area: 'task', name: 'Tasks', mod: 'tasks', icon: 'icon-list-checks', perms: [['task.read', 'See tasks you raised or were assigned'], ['task.read_all', 'See everybody’s tasks, not only your own'], ['task.create', 'Raise a task'], ['task.update', 'Change a task’s detail, and move it through its states'], ['task.assign', 'Give a task to somebody else, or take one on'], ['task.comment', 'Say something on a task, and name colleagues in it'], ['task.delete', 'Remove a task entirely. Cancelling one keeps the record; this does not.']] },
  { area: 'invoice', name: 'Invoices', mod: 'billing', icon: 'icon-file-text', perms: [['invoice.read', 'See invoices and their figures'], ['invoice.create', 'Draft an invoice'], ['invoice.update_draft', 'Change an invoice that is still a draft'], ['invoice.approve', 'Approve an invoice someone else submitted'], ['invoice.approve_own', 'Approve an invoice you drafted yourself'], ['invoice.reject', 'Send an invoice back to its author'], ['invoice.issue', 'Issue an approved invoice, allocating its number and locking its figures'], ['invoice.send', 'Send an issued invoice to the customer'], ['invoice.cancel', 'Cancel an invoice before it has been issued'], ['invoice.void', 'Void an issued invoice, which cancels a document the customer already has'], ['invoice.export', 'Export invoices to CSV'], ['invoice.correct', 'Correct an issued invoice directly. Rare, controlled, and fully audited.']] },
  { area: 'credit_note', name: 'Credit notes', mod: 'billing', icon: 'icon-receipt', perms: [['credit_note.read', 'See credit notes and what they offset'], ['credit_note.create', 'Draft a credit note against an issued invoice'], ['credit_note.issue', 'Issue a credit note, which reduces what the customer owes']] },
  { area: 'payment', name: 'Payments', mod: 'payments', icon: 'icon-wallet', perms: [['payment.read', 'See payments received and how they were allocated'], ['payment.create', 'Record a payment received from a customer'], ['payment.update', 'Change the details of a recorded payment'], ['payment.allocate', 'Allocate a received payment against invoices'], ['payment.reverse', 'Reverse a payment and restore the invoice balances it settled']] },
  { area: 'asset', name: 'Assets', mod: 'assets', icon: 'icon-laptop', perms: [['asset.read', 'See equipment and who holds it'], ['asset.assign', 'Assign equipment to people and projects, and take it back'], ['asset.manage', 'Add, value and write off equipment']] },
  { area: 'document', name: 'Documents', mod: 'documents', icon: 'icon-folder', perms: [['document.read', 'Open and download stored documents and PDFs'], ['document.create', 'Upload attachments and generate PDFs'], ['document.delete', 'Delete a stored document']] },
  { area: 'approval', name: 'Approvals', mod: 'approvals', icon: 'icon-badge-check', perms: [['approval.read', 'See the approval queue'], ['approval.decide', 'Approve or reject what policy routes to you']] },
  { area: 'report', name: 'Reports', mod: 'reports', icon: 'icon-chart-column', perms: [['report.read', 'See the dashboard and the reports'], ['report.export', 'Export a report to CSV']] },
  { area: 'ai', name: 'AI assistant', mod: 'ai', icon: 'icon-sparkles', perms: [['ai.use', 'Ask the assistant about records you can already see'], ['ai.act', 'Let the assistant make changes after you confirm them']] },
  { area: 'admin', name: 'Administration', mod: null, icon: 'icon-shield', perms: [['user.read', 'See who belongs to the organisation and what their access covers'], ['user.invite', 'Send and revoke invitations to join'], ['user.manage', 'Add and remove people, change their roles and status'], ['role.read', 'See the roles and what each one may do'], ['role.manage', 'Define roles and choose the permissions they carry'], ['organization.update', 'Change the organisation’s name, currency and time zone'], ['settings.manage', 'Change organisation-wide settings'], ['numbering.manage', 'Change how documents are numbered'], ['template.manage', 'Change invoice and quotation templates'], ['audit.read', 'Read the audit log']] },
];
export const ALL_PERMS: string[] = PERM_GROUPS.flatMap(g => g.perms.map(p => p[0]));
export const MOD_PERM: Record<string, string> = { crm: 'customer.read', sales: 'quote.read', projects: 'project.read', tasks: 'task.read', billing: 'invoice.read', payments: 'payment.read', assets: 'asset.read', documents: 'document.read', approvals: 'approval.read', reports: 'report.read', ai: 'ai.use' };
/** Which module a permission area belongs to (null = always available). */
export const AREA_MODULE: Record<string, string | null> = Object.fromEntries(PERM_GROUPS.flatMap(g => g.perms.map(([k]) => [k.split('.')[0], g.mod])));

const ex = (areas: string[]) => ALL_PERMS.filter(k => areas.includes(k.split('.')[0]));
export const DEFAULT_ROLES: { name: string; builtIn?: boolean; desc: string; perms: string[] }[] = [
  { name: 'Owner', builtIn: true, desc: 'Everything, including settings and billing. Built in, and can’t be narrowed.', perms: ALL_PERMS },
  { name: 'Project manager', desc: 'Runs projects and their people. Drafts quotations and invoices, and administers this workspace.', perms: [...ex(['project', 'task', 'approval', 'ai']), 'customer.read', 'customer.create', 'customer.update', 'quote.read', 'quote.create', 'quote.update', 'quote.send', 'quote.convert', 'catalog.read', 'invoice.read', 'invoice.create', 'invoice.update_draft', 'invoice.send', 'credit_note.read', 'credit_note.create', 'payment.read', 'asset.read', 'asset.assign', 'document.read', 'document.create', 'report.read', 'user.read', 'user.invite', 'user.manage', 'role.read', 'role.manage', 'organization.update', 'settings.manage', 'numbering.manage', 'template.manage', 'audit.read'] },
  { name: 'Sales', desc: 'Owns customers, the pipeline and the catalogue, and drafts quotations.', perms: [...ex(['customer', 'catalog']), 'quote.read', 'quote.create', 'quote.update', 'quote.reject', 'quote.send', 'quote.convert', 'project.read', 'task.read', 'task.create', 'task.update', 'task.comment', 'task.assign', 'invoice.read', 'document.read', 'document.create', 'approval.read', 'approval.decide', 'report.read', 'ai.use'] },
  { name: 'Finance', desc: 'Approves, issues and collects. Owns credit notes and payments.', perms: [...ex(['credit_note', 'payment', 'document', 'approval', 'report']), ...ex(['invoice']).filter(k => k !== 'invoice.correct'), 'customer.read', 'customer.update', 'quote.read', 'catalog.read', 'project.read', 'task.read', 'task.create', 'task.update', 'task.comment', 'asset.read', 'ai.use', 'audit.read'] },
  { name: 'Field staff', desc: 'Works the tasks and projects they are assigned.', perms: ['project.read', 'task.read', 'task.create', 'task.update', 'task.comment', 'asset.read', 'document.read', 'ai.use'] },
];

const ACT_LABEL: Record<string, string> = { read: 'View', read_all: 'View everyone’s', create: 'Create', update: 'Edit', update_draft: 'Edit drafts', archive: 'Archive', approve: 'Approve', approve_own: 'Approve own', reject: 'Send back', send: 'Send', convert: 'Convert', change_owner: 'Change owner', assign_members: 'Assign members', assign: 'Assign', comment: 'Comment', delete: 'Delete', issue: 'Issue', cancel: 'Cancel', void: 'Void', export: 'Export', correct: 'Correct issued', allocate: 'Allocate', reverse: 'Reverse', manage: 'Manage', invite: 'Invite', decide: 'Decide', use: 'Use', act: 'Act on confirmation' };
const AREA_LABEL: Record<string, string> = { user: 'Users', role: 'Roles', organization: 'Organisation', settings: 'Settings', numbering: 'Numbering', template: 'Templates', audit: 'Audit log' };
export const permLabel = (k: string): string => {
  const [a, act] = k.split('.'); const l = ACT_LABEL[act] || act;
  return AREA_LABEL[a] ? `${AREA_LABEL[a]}: ${l.toLowerCase()}` : l;
};
